theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.21
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.21/clink.1.9.21.3cc8b4.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.21/clink.1.9.21.3cc8b4_setup.exe
