theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.23
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.23/clink.1.9.23.37616c.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.23/clink.1.9.23.37616c_setup.exe
