theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.9.26
  download_url: https://github.com/chrisant996/clink/releases/download/v1.9.26/clink.1.9.26.ac0bbf.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.9.26/clink.1.9.26.ac0bbf_setup.exe
